### ISSUE TITLE
Faulty Windows build

### ISSUE THREAD

**Issue by cravenge** [shqke/impactfix#2]
This extension really looks promising but my dedicated server suffers from random crashes once it gets installed. I am using SourceMod 1.10 if it helps. I also have these crash logs from Accelerator for further details:

> 0    server.dll + 0x27207
1    server.dll + 0x79252
2    0x1ab559fe
3    bintools.ext.dll!CallWrapper::Execute(void *,void *) [CallWrapper.cpp:144 + 0xb] 
4    impactfix.ext.2.l4d2.dll + 0x2870
5    server.dll + 0x356eab
6    server.dll + 0x2cf74a
7    server.dll + 0x2d061d
8    server.dll + 0x2d16b4
9    server.dll + 0x2d20a8
10    server.dll + 0xf8073
11    server.dll + 0xfb22f
12    server.dll + 0x2cefb4
13    server.dll + 0xf44fc
14    server.dll + 0x2358c6
15    server.dll + 0x2cd9ab
16    server.dll + 0x17e8bc
17    server.dll + 0x16dc65
18    server.dll + 0x23f264
19    server.dll + 0x30e92a
20    sdktools.ext.2.l4d2.dll!SourceHook_MFHCls_PlayerRunCmdHook::Func(CUserCmd *,IMoveHelper *) [hooks.cpp:50 + 0xab] 
21    server.dll + 0x17d2c6
22    server.dll + 0x38a049
23    server.dll + 0x144254
24    server.dll + 0xeddeb
25    sourcemod.2.l4d2.dll!SourceHook_FHCls_IServerGameDLLGameFramefalse::Func(bool) [sourcemod.cpp:54 + 0xa3] 
26    engine.dll + 0x124577
27    engine.dll + 0x1256b7
28    engine.dll + 0x18f398
29    engine.dll + 0x190c06
30    engine.dll + 0x191363
31    engine.dll + 0x1a0a2b
32    engine.dll + 0x1a0b7f
33    engine.dll + 0x1a0c24
34    engine.dll + 0x200cf4
35    engine.dll + 0x1fe311
36    dedicated.dll + 0x31ce
37    dedicated.dll + 0x3906
38    dedicated.dll + 0x27dae
39    dedicated.dll + 0x4976
40    srcds.exe + 0x11fd
41    srcds.exe + 0x1929
42    kernel32.dll!BaseThreadInitThunk + 0x19
43    ntdll.dll!__RtlUserThreadStart + 0x2f
44    ntdll.dll!_RtlUserThreadStart + 0x1b

**Comment by shqke** [comment]
Windows offsets were incorrect, I've pushed an update.

I don't know what kind of conflict can l4d2_bugfixes extension have with this extension, they do not seem to have anything in common by quick look at the code.

Thanks for report!

**Comment by cravenge** [comment]
> Windows offsets were incorrect, I've pushed an update.
> 
> I don't know what kind of conflict can l4d2_bugfixes extension have with this extension, they do not seem to have anything in common by quick look at the code.
> 
> Thanks for report!

Oh, I was under the impression that they were incompatible with each other since the server crashes almost immediately with both installed. Anyways, it looks like it's stable now.
